version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/var/lib/mysql" # this is how we persist a sql db even when container stops
  www:
    image: php:7.2-apache
    volumes:
      - "./html:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 50300:80
      - 50301:443 # for future ssl traffic
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 50302:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306